apiVersion: v1
kind: Secret
metadata:
  name: giftlink-secrets
type: Opaque
stringData:
  MONGO_URL: "mongodb://mongodb:27017"
  JWT_SECRET: "change_this_in_production"
  SENTIMENT_URL: "http://sentiment-service:3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  labels:
    app: backend-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: giftlink-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3060
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: giftlink-secrets
              key: MONGO_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: giftlink-secrets
              key: JWT_SECRET
        - name: SENTIMENT_URL
          valueFrom:
            secretKeyRef:
              name: giftlink-secrets
              key: SENTIMENT_URL
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api
spec:
  selector:
    app: backend-api
  ports:
  - port: 3060
    targetPort: 3060
  type: ClusterIP